<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);

$fieldVal = array();
foreach($this->item->jcfields as $field) :
	$fieldVal[$field->name] = $field->value;
	$fieldPar[$field->name] = $field->fieldparams;
	$fieldRaw[$field->name] = $field->rawvalue;
	$fieldTitle[$field->name] = $field->title;
	$fieldTitleClass[$field->name] = $field->params->get('label_render_class');
	$fieldClass[$field->name] = $field->params->get('render_class');
endforeach;
$fieldOptServ = $fieldPar['services']->get('options');
$fieldOptAddServ= $fieldPar['addservices']->get('options');
$fieldGall = json_decode($fieldRaw['gallery'], true);
// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
<div class="room-page<?=$this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?=($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if ($this->params->get('show_page_heading')) : ?>
	<div class="page-title"><h1><?=$this->escape($this->params->get('page_heading')); ?></h1></div>
	<?php endif;
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
	{
		echo $this->item->pagination;
	}
	?>
	<?php // Todo Not that elegant would be nice to group the params ?>
	<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if (!$useDefList && $this->print) : ?>
		<div id="pop-print" class="btn hidden-print">
			<?=JHtml::_('icon.print_screen', $this->item, $params); ?>
		</div>
		<div class="clearfix"> </div>
	<?php endif; ?>
	<?php if ($params->get('show_title') || $params->get('show_author')) : ?>
	<h2 class="page-title" itemprop="headline"><?php if ($params->get('show_title')) : ?><?=JText::_('ROOM') .' &laquo;'. $this->escape($this->item->title) .'&raquo;'; ?><?php endif; ?></h2>

		<?php if ($this->item->state == 0) : ?>
			<span class="label label-warning"><?=JText::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
			<span class="label label-warning"><?=JText::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
			<span class="label label-warning"><?=JText::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	
	<?php endif; ?>
	<?php if (!$this->print) : ?>
		<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
			<?=JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
		<?php endif; ?>
	<?php else : ?>
		<?php if ($useDefList) : ?>
			<div id="pop-print" class="btn hidden-print">
				<?=JHtml::_('icon.print_screen', $this->item, $params); ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?=$this->item->event->afterDisplayTitle; ?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
		<?=JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>

		<?=$this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?=$this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?=$this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>

	<?php //JLayoutHelper::render('joomla.content.full_image', $this->item); ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	endif;
	?>
	<?php if (isset ($this->item->toc)) :
		echo $this->item->toc;
	endif; ?>
	<div class="room-item" itemprop="articleBody">
		<div class="row block">
		<?php if (isset($fieldGall) && !empty($fieldGall) ): ?>
			<div class="col-md-<?php if(isset($fieldGall)) : echo '7'; endif; ?> gallery">
				<div class="gallery-big" id="gallery-big">
					<?php foreach ($fieldGall as $fValGall) : ?>
					<?php if (isset($fValGall['big']) && !empty($fValGall['big']) ): ?>
					<?php
						// из ссылки вырезаем каталог
						$path_dirname = pathinfo($fValGall['big'])['dirname'];
						$path_basename = pathinfo($fValGall['big'])['basename'];
						$path_infoName = pathinfo($path_dirname, PATHINFO_DIRNAME);
					?>		
						<div class="img"><a href="<?=$path_infoName.'/'.$path_basename?>"><img src="<?=$fValGall['big']; ?>" alt="<?=$fValGall['alt']; ?>"></a></div>
					<?php endif; ?>
					<?php endforeach; ?>
				</div>
				<div class="gallery-mini" id="gallery-mini">
					<?php foreach ($fieldGall as $fValGall) : ?>
					<?php if (isset($fValGall['mini']) && !empty($fValGall['mini']) ): ?>
						<div class="img"><img src="<?=$fValGall['mini']; ?>" alt="mini_<?=$fValGall['alt']; ?>"></div>
					<?php endif; ?>	
					<?php endforeach; ?>
				</div>
			</div>
		<?php endif; ?>
		

			<div class="col-md-<?php if(isset($fieldGall)) : echo '5'; else : echo '12'; endif; ?> item-form">
				<?=JHtml::_('content.prepare', '{rsform 1}'); ?>
			</div>
		</div>
		<div class="block short">
			<div class="container">
				<div class="row">
				<?php if (!empty($fieldVal['square']) || !empty($fieldVal['bed']) || !empty($fieldVal['plan'])) : ?>
					<ul>
						<?php if (!empty($fieldVal['square']) && isset($fieldVal['square'])) : ?>
						<li data-toggle="tooltip" data-placement="top" title="<?=JText::_('ROOM_AREA'); ?>">
							<i class="fa-<?=$fieldClass['square']; ?>"></i><span><?=$fieldVal['square']; ?>м<sup>2</sup></span>
						</li>
						<?php endif; ?>
						<?php if (!empty($fieldVal['bed']) && isset($fieldVal['bed'])) : ?>
						<li data-toggle="tooltip" data-placement="top" title="<?=JText::_('BEDS_ROOM'); ?>">
							<i class="fa-<?=$fieldClass['bed']; ?>"></i><span><?=$fieldVal['bed']; ?></span>
						</li>
						<?php endif; ?>	

						<?php if (!empty($fieldVal['plan']) && isset($fieldVal['plan'])) : ?>
						<li data-toggle="tooltip" data-placement="top" title="<?=JText::_('ROOM_PLAN'); ?>">
							<a href="<?=$fieldRaw['plan']; ?>"><i class="fa-<?=$fieldClass['plan']; ?>"></i></a>
						</li>
						<?php endif; ?>	
					</ul>
				<?php endif; ?>	
				</div>
			</div>
		</div>
		<?php if (isset($this->item->text) && !empty($this->item->text)) : ?>
		<div class="row block">
			<div class="full item-text"><?=$this->item->text; ?></div>
		</div>
		<?php endif; ?>	
		<div class="block item-services">
			<div class="container">
				<div class="row">
				<?php /*проверка на пустоту полей у материала, но даные берем глобальные и проверяем с данными материала - проверяем сходство = выводим*/?>		
					<?php if (isset($fieldVal['services']) && !empty($fieldVal['services']) || isset($fieldVal['addservices']) && !empty($fieldVal['addservices'])) : ?>
					<div class="col-md-<?php if(isset($fieldVal['services'])) : echo '5'; endif; ?> over">
						<h3 class="<?=$fieldTitleClass['services']; ?>"><?=$fieldTitle['services']; ?></h3>
						<div class="list-services">
						<?php foreach ($fieldOptServ as $foption) : ?>
							<?php foreach ($fieldRaw['services'] as $fRaw) : ?>
								<?php if($fRaw == $foption->value): ?>
								<dl>
									<dt><i class="fa-<?=$foption->value; ?>"></i></dt>
									<dd><?=$foption->name; ?></dd>
								</dl>	
								<?php endif; ?>
							<?php endforeach; ?>
						<?php endforeach; ?>
						</div>
					</div>
					<?php endif; ?>
					<?php if (isset($fieldRaw['addservices']) && !empty($fieldRaw['addservices'])) : ?>
					<div class="col-md-<?php if(isset($fieldVal['services'])) : echo '7'; else : echo '12'; endif; ?> leter">
						<h3 class="<?=$fieldTitleClass['addservices']; ?>"><?=$fieldTitle['addservices']; ?></h3>
						<div class="list-services">
							<?php foreach ($fieldOptAddServ as $foption) : ?>
								<?php foreach ($fieldRaw['addservices'] as $fRaw) : ?>
									<?php if($fRaw == $foption->value): ?>
									<dl>
										<dt><i class="fa-<?=$foption->value; ?>"></i></dt>
										<dd><?=$foption->name; ?></dd>
									</dl>	
									<?php endif; ?>
								<?php endforeach; ?>
							<?php endforeach; ?>
						</div>						
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<?php if (isset($fieldRaw['booking']) && !empty($fieldRaw['booking'])) : ?>
		<div class="row block">
			<div class="booking">
				<?=($fieldRaw['booking']); ?>
			</div>
		</div>
		<?php endif; ?>
	<?php // end room-item?>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
			<?=JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
			<?=$this->item->tagLayout->render($this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
	<?=$this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests ?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?=JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?=JHtml::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article. ?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = JFactory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<p class="readmore">
		<a href="<?=$link; ?>" class="register">
		<?php $attribs = json_decode($this->item->attribs); ?>
		<?php
		if ($attribs->alternative_readmore == null) :
			echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
		elseif ($readmore = $attribs->alternative_readmore) :
			echo $readmore;
			if ($params->get('show_readmore_title', 0) != 0) :
				echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
			endif;
		elseif ($params->get('show_readmore_title', 0) == 0) :
			echo JText::sprintf('COM_CONTENT_READ_MORE_TITLE');
		else :
			echo JText::_('COM_CONTENT_READ_MORE');
			echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
		endif; ?>
		</a>
	</p>
	<?php endif; ?>
	<?php endif; ?>
	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?=$this->item->event->afterDisplayContent; ?>
</div>
